name: health_financer
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_auth: 
  cloud_firestore: 
  font_awesome_flutter:
  google_fonts:
  cupertino_icons: ^0.1.2
# 
  flutter:
    sdk: flutter
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # font_awesome_flutter: ^8.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dashboard.png
    - assets/images/hf_logo.png